---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
helmCharts:
  - name: longhorn
    namespace: longhorn
    includeCRDs: true
    releaseName: longhorn
    version: 1.7.2
    repo: https://charts.longhorn.io