---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
helmCharts:
  - name: longhorn
    namespace: longhorn
    includeCRDs: true
    releaseName: longhorn
    version: v1.7.1
    repo: hhttps://charts.longhorn.io