apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: logging
spec:
    interval: 5m
    driftDetection:
        mode: enabled
    chart:
        spec:
            chart: loki
            version: 6.33.0
            sourceRef:
                kind: HelmRepository
                name: loki
                namespace: logging