---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/thanos/thanos
    newTag: v0.41.0
  - name: docker.io/grafana/grafana
    newTag: 12.4.4
  - name: docker.io/prom/memcached-exporter
    newTag: v0.16.0
  - name: docker.io/nginxinc/nginx-unprivileged
    newTag: 1.31-alpine
  - name: quay.io/prometheus/alertmanager
    newTag: v0.33.0
  - name: docker.io/prom/prometheus
    newTag: v3.13.0
  - name: docker.io/kiwigrid/k8s-sidecar
    newTag: 2.7.3
