---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: traefik
    namespace: traefik
spec:
    interval: 30m
    chart:
        spec:
            chart: traefik
            version: v30.1.0
            sourceRef:
                kind: HelmRepository
                name: traefik
                namespace: traefik
            interval: 12h
    install:
        crds: CreateReplace
    upgrade:
        crds: CreateReplace