---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
helmCharts:
  - name: traefik
    namespace: traefik
    includeCRDs: true
    releaseName: traefik
    version: 32.0.0
    repo: https://traefik.github.io/charts