---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    namespace: traefik-v2
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: traefik
    version: v28.3.0
    repo: https://traefik.github.io/charts
