---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
helmCharts:
  - name: traefik
    namespace: traefik-v2
    includeCRDs: true
    releaseName: traefik
    version: 30.0.2
    repo: https://traefik.github.io/charts
