---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
helmCharts:
  - name: traefik
    namespace: traefik
    includeCRDs: true
    releaseName: traefik
    version: 37.0.0
    repo: https://traefik.github.io/charts

images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.11.0