---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaduzzcloud
    namespace: nextcloud
spec:
    interval: 10m
    driftDetection:
        mode: enabled
    chart:
        spec:
            chart: nextcloud
            version: 6.6.6
            sourceRef:
                kind: HelmRepository
                name: nextcloud
                namespace: nextcloud
            interval: 2h