apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 10m0s
    releaseName: authentik
    chart:
        spec:
            chart: authentik
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: authentik
            version: 2025.6.2
    values: null
