apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 10m0s  # Sync interval between Flux and the Helm repository
  url: https://prometheus-community.github.io/helm-charts