apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 10m0s
    releaseName: kube-prometheus-stack
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: monitoring
            version: 70.7.0
    install:
        createNamespace: true