---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    namespace: connect
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: connect
    version: 1.15.1
    repo: https://1password.github.io/connect-helm-charts/
