---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: hcloud-csi
    namespace: kube-system
spec:
    interval: 10m
    driftDetection:
        mode: enabled
    chart:
        spec:
            chart: hcloud-csi
            version: 2.16.0
            sourceRef:
                kind: HelmRepository
                name: hcloud
                namespace: kube-system
            interval: 2h
