apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wekan
  namespace: wekan
spec:
  interval: 10m0s  # Sync interval between Flux and the Helm repository
  url: https://wekan.github.io/charts