---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-hansonauten
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: 4.26.3
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
      interval: 10m