---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-hansonauten
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: 4.23.7
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
      interval: 10m