---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: minecraft
    namespace: minecraft
spec:
    interval: 10m0s
    url: https://itzg.github.io/minecraft-server-charts/