apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: wireguard
    namespace: wireguard
spec:
    interval: 10m0s
    releaseName: wireguard
    chart:
        spec:
            chart: wireguard
            sourceRef:
                kind: HelmRepository
                name: wireguard
                namespace: wireguard
            version: 0.30.0
    values: null
